export const ADMIN_NAME = 'GUVANCH'
export const ADMIN_PASSWORD = 'GUVANCH99'
export const ALL_PRODUCTS = '/all-products'
export const PRICE = 'price'
export const BONUS='bonus'
export const ORDERS = '/orders'
export const NEXT_ID = 2
export const EXPECTED_INCOME=500
export const HUNDRED_PERCENT=100
export const FIRST_SEGMENT_OFF_SET=25